name: Update Sidebar
on:
  schedule:
    - cron: '0 8 * * *'
  issues:
    types: [pinned]
  workflow_call:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: junxnone/autosidebar@main
        with:
          push_branch: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          actor: ${{ github.actor }}
          docs_path: "docs"
          root_node: "AIwiki"
